- name: install pip
  yum: name=python2-pip

- name: install docker-py
  pip: name=docker-py

- name: start a Portainer container
  docker_container:
    image: imflop/portainer-fork:linux-amd64-latest
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    name: portainer
    restart_policy: always
    state: started
    network_mode: host
    log_options:
        max-size: 200m
        max-file: 2
